name: jaffle_shop
version: '0.1'
profile: jaffle_shop_neon
config-version: 2
model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_modules
  - logs
models:
  jaffle_shop:
    +schema: marts  # Default schema for final models
    +materialized: table
    staging:
      +schema: staging
      +materialized: view
    fanouts_examples:
      +schema: specialized
      +meta:
        group_label: fanouts
    campaigns:
      +meta:
        group_label: campaigns
    marketing_touchpoints:
      +schema: specialized
      +meta:
        group_label: campaigns
    patient_health_scores:
      +schema: specialized
      +meta:
        group_label: healthcare
    visit_analytics:
      +schema: specialized
      +meta:
        group_label: healthcare
    generated_a:
      +schema: specialized
    generated_b:
      +schema: specialized
    generated_budgets:
      +schema: specialized
seeds:
  jaffle_shop:
    +schema: raw  # All seeds go to raw schema
    raw_customers:
      +column_types:
        created: timestamp
    raw_orders:
      +column_types:
        order_date: date
        estimated_delivery_days: integer
        shipping_cost: numeric
        tax_rate: numeric
    raw_plan:
      +column_types:
        metadata: jsonb
    raw_tracks:
      +column_types:
        timestamp: timestamp
